# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ 1.2 ]
  pull_request:
    branches: [ 1.2 ]

jobs:
  default:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i
    - run: npm run build --if-present
    - run: npm test


  ol-versions:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ol-version: [ '6.6', '6.7', '6.8', '6.9' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i ol@${{ matrix.ol-version }} react@16.14 react-dom@16.14 react-test-renderer@16.14
    - run: npm i
    - run: tsc
    - run: npm test -- -u


  react-versions:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        react-version: [ '16.8', '16.14', '17.0.2' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i ol
    - run: npm --force i react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} react-test-renderer@${{ matrix.react-version }}
    - run: npm i
    - run: tsc
    - run: npm test


  codecov:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i
    - run: npm run test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - run: npm run codecov
